# Generated by Django 3.0.8 on 2020-11-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Bio',
            new_name='bio',
        ),
    ]
